UPDATE part SET p_size = 7 WHERE p_partkey = 1;
UPDATE part SET p_container = 'LG CASE' WHERE p_partkey = 2;
UPDATE part SET p_retailprice = 903.00 WHERE p_partkey = 3;
UPDATE part SET p_container = 'MED DRUM' WHERE p_partkey = 4;
UPDATE part SET p_mfgr = 'Manufacturer#3' WHERE p_partkey = 5;
UPDATE part SET p_container = 'MED BAG' WHERE p_partkey = 6;
UPDATE part SET p_mfgr = 'Manufacturer#1' WHERE p_partkey = 7;
UPDATE part SET p_comment = 'eposi' WHERE p_partkey = 8;
UPDATE part SET p_comment = 'ironic foxe' WHERE p_partkey = 9;
UPDATE part SET p_comment = 'ithely final deposit' WHERE p_partkey = 10;
UPDATE supplier SET s_comment = ' slyly bold instructions. idle dependen' WHERE s_suppkey = 2;
UPDATE supplier SET s_acctbal = 4192.40 WHERE s_suppkey = 3;
UPDATE supplier SET s_phone = '25-843-787-7479' WHERE s_suppkey = 4;
UPDATE supplier SET s_acctbal = -283.84 WHERE s_suppkey = 5;
UPDATE supplier SET s_comment = 'final accounts. regular dolphins use against the furiously ironic decoys. ' WHERE s_suppkey = 6;
UPDATE supplier SET s_phone = '20-403-398-8662' WHERE s_suppkey = 9;
UPDATE supplier SET s_comment = 'al packages nag alongside of the bold instructions. express, daring accounts' WHERE s_suppkey = 12;
UPDATE supplier SET s_address = 'HK71HQyWoqRWOX8GI FpgAifW,2PoH' WHERE s_suppkey = 13;
UPDATE supplier SET s_comment = 'l accounts boost. fluffily bold warhorses wake' WHERE s_suppkey = 14;
UPDATE supplier SET s_name = 'Supplier#000000015' WHERE s_suppkey = 15;
UPDATE supplier SET s_phone = '13-715-945-6730' WHERE s_suppkey = 20;
UPDATE supplier SET s_phone = '12-253-590-5816' WHERE s_suppkey = 21;
UPDATE supplier SET s_address = 'okiiQFk 8lm6EVX6Q0,bEcO' WHERE s_suppkey = 22;
UPDATE supplier SET s_address = 'ssetugTcXc096qlD7 2TL5crEEeS3zk' WHERE s_suppkey = 23;
UPDATE supplier SET s_name = 'Supplier#000000024' WHERE s_suppkey = 24;
UPDATE supplier SET s_name = 'Supplier#000000028' WHERE s_suppkey = 28;
UPDATE partsupp SET ps_supplycost = 771.64 WHERE ps_partkey = 1;
UPDATE partsupp SET ps_supplycost = 378.49 WHERE ps_partkey = 2;
UPDATE partsupp SET ps_availqty = 4969 WHERE ps_partkey = 2;
UPDATE partsupp SET ps_supplycost = 920.92 WHERE ps_partkey = 3;
UPDATE partsupp SET ps_availqty = 1339 WHERE ps_partkey = 4;
UPDATE partsupp SET ps_availqty = 3735 WHERE ps_partkey = 5;
UPDATE partsupp SET ps_availqty = 6834 WHERE ps_partkey = 8;
UPDATE partsupp SET ps_availqty = 4540 WHERE ps_partkey = 11;
UPDATE partsupp SET ps_comment = 'jole bold theodolites. final packages haggle! carefully regular deposits play furiously among the special ideas. quickly ironic packages detect quickly carefully final' WHERE ps_partkey = 12;
UPDATE partsupp SET ps_supplycost = 169.44 WHERE ps_partkey = 13;
UPDATE partsupp SET ps_availqty = 5278 WHERE ps_partkey = 14;
UPDATE partsupp SET ps_supplycost = 144.80 WHERE ps_partkey = 19;
UPDATE partsupp SET ps_comment = 's, ironic deposits haggle across the quickly bold asymptotes. express, ironic pinto beans wake carefully enticingly special foxes. requests are at the c' WHERE ps_partkey = 20;
UPDATE partsupp SET ps_availqty = 6571 WHERE ps_partkey = 21;
UPDATE partsupp SET ps_availqty = 4410 WHERE ps_partkey = 22;
UPDATE partsupp SET ps_availqty = 2739 WHERE ps_partkey = 23;
UPDATE partsupp SET ps_comment = ' behind the blithely regular courts impress after the silent sheaves. bravely final ideas haggle ' WHERE ps_partkey = 26;
UPDATE partsupp SET ps_supplycost = 444.01 WHERE ps_partkey = 27;
UPDATE partsupp SET ps_comment = 'ound the final foxes detect furiously across the even warhorses. quickly t' WHERE ps_partkey = 27;
UPDATE partsupp SET ps_supplycost = 666.53 WHERE ps_partkey = 28;
UPDATE partsupp SET ps_availqty = 6252 WHERE ps_partkey = 29;
UPDATE partsupp SET ps_comment = ' sleep. bold, regular deposits hang doggedly furiously bold requests. slyly bold excuses detect busily above the even gifts. blithely express courts are carefully. blithely final packages until th' WHERE ps_partkey = 30;
UPDATE customer SET c_address = 'IVhzIApeRb ot,c,E' WHERE c_custkey = 1;
UPDATE customer SET c_comment = 'l accounts. blithely ironic theodolites integrate boldly: caref' WHERE c_custkey = 2;
UPDATE customer SET c_mktsegment = 'AUTOMOBILE' WHERE c_custkey = 3;
UPDATE customer SET c_comment = ' requests. final, regular ideas sleep final accou' WHERE c_custkey = 4;
UPDATE customer SET c_comment = 'n accounts will have to unwind. foxes cajole accor' WHERE c_custkey = 5;
UPDATE customer SET c_comment = 'r theodolites according to the requests wake thinly excuses: pending requests haggle furiousl' WHERE c_custkey = 9;
UPDATE customer SET c_acctbal = 2753.54 WHERE c_custkey = 10;
UPDATE customer SET c_comment = ' to the carefully final braids. blithely regular requests nag. ironic theodolites boost quickly along' WHERE c_custkey = 12;
UPDATE customer SET c_acctbal = 3857.34 WHERE c_custkey = 13;
UPDATE customer SET c_name = 'Customer#000000014' WHERE c_custkey = 14;
UPDATE orders SET o_comment = ' express deposits along the blithely regul' WHERE o_orderkey = 71;
UPDATE orders SET o_clerk = 'Clerk#000000642' WHERE o_orderkey = 224;
UPDATE orders SET o_clerk = 'Clerk#000000573' WHERE o_orderkey = 320;
UPDATE orders SET o_comment = 'l, silent instructions are slyly. silently even de' WHERE o_orderkey = 358;
UPDATE orders SET o_orderstatus = 'O' WHERE o_orderkey = 387;
UPDATE orders SET o_orderstatus = 'O' WHERE o_orderkey = 739;
UPDATE orders SET o_orderpriority = '1-URGENT' WHERE o_orderkey = 896;
UPDATE orders SET o_orderpriority = '5-LOW' WHERE o_orderkey = 994;
UPDATE orders SET o_orderstatus = 'F' WHERE o_orderkey = 1031;
UPDATE orders SET o_orderpriority = '2-HIGH' WHERE o_orderkey = 1475;
UPDATE orders SET o_orderpriority = '5-LOW' WHERE o_orderkey = 1602;
UPDATE orders SET o_totalprice = 46920.46 WHERE o_orderkey = 1603;
UPDATE orders SET o_orderstatus = 'O' WHERE o_orderkey = 1635;
UPDATE orders SET o_clerk = 'Clerk#000000103' WHERE o_orderkey = 1667;
UPDATE orders SET o_orderpriority = '4-NOT SPECIFIED' WHERE o_orderkey = 2374;
UPDATE orders SET o_orderdate = '1996-11-20' WHERE o_orderkey = 2375;
UPDATE orders SET o_orderpriority = '3-MEDIUM' WHERE o_orderkey = 2980;
UPDATE orders SET o_shippriority = 0 WHERE o_orderkey = 3266;
UPDATE orders SET o_orderstatus = 'O' WHERE o_orderkey = 3329;
UPDATE orders SET o_orderdate = '1997-05-29' WHERE o_orderkey = 3427;
UPDATE orders SET o_orderdate = '1996-12-26' WHERE o_orderkey = 3623;
UPDATE orders SET o_orderstatus = 'O' WHERE o_orderkey = 4100;
UPDATE orders SET o_comment = 'special foxes affix never blithely ironic pinto beans; blithely ' WHERE o_orderkey = 4165;
UPDATE orders SET o_shippriority = 0 WHERE o_orderkey = 4193;
UPDATE orders SET o_clerk = 'Clerk#000000309' WHERE o_orderkey = 4199;
UPDATE orders SET o_shippriority = 0 WHERE o_orderkey = 4263;
UPDATE orders SET o_orderpriority = '1-URGENT' WHERE o_orderkey = 4355;
UPDATE orders SET o_comment = 'inal pinto beans. exp' WHERE o_orderkey = 4390;
UPDATE orders SET o_shippriority = 0 WHERE o_orderkey = 4704;
UPDATE orders SET o_comment = 'ave accounts. furiously pending wa' WHERE o_orderkey = 4806;
UPDATE orders SET o_orderstatus = 'F' WHERE o_orderkey = 4928;
UPDATE lineitem SET l_quantity = 25 WHERE l_orderkey = 2374;
UPDATE lineitem SET l_extendedprice = 11804.00 WHERE l_orderkey = 4355;
